version: "3.8"

services:
  bot:
    container_name: donor-guide-bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      RESEND_CHAT_ID: ${RESEND_CHAT_ID}
      LOG_LEVEL: ${LOG_LEVEL}
    volumes:
      - ./src:/app/src
    networks:
      - donor-guide-network
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - donor-guide-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "secret_admin_password"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5434:80"
    depends_on:
      - postgres
    networks:
      - donor-guide-network

volumes:
  postgres_data:

networks:
  donor-guide-network:
    driver: bridge