"""add default to is_active

Revision ID: d3ababfd2963
Revises: c789b1b047c2
Create Date: 2025-04-21 22:45:13.248126

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d3ababfd2963"
down_revision: Union[str, None] = "c789b1b047c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column("questions", "is_active", server_default="true")
    op.alter_column("folders", "is_active", server_default="true")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("questions", "answer_text", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("questions", "folder_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column("questions", "is_active", server_default=None)
    op.alter_column("folders", "is_active", server_default=None)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("questions", "folder_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("questions", "answer_text", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
